import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-6xl mx-auto`}
      >
<header>
      <div className='w-full py-3 border-b'>

        <div className='flex justify-between items-center font-semibold'>
          <div>
            <h1 className="text-2xl">LOGO</h1>
          </div>
          <nav className='flex xl:gap-10 md:gap-8  gap-2'>

            <Link href={'/'}> Home </Link>  
          
          </nav>
          <div>
          <Link href={'/sing-up'}>
                <button className='py-2 px-6 bg-black text-white rounded-3xl font-semibold cursor-pointer'>
                   Sign In
                </button> 
            </Link>

            <Link href={'/sing-in'}>
                <button className='py-2 px-6 bg-black text-white rounded-3xl font-semibold cursor-pointer'>
                   Sign Up
                </button> 
            </Link>
          </div>
        </div>
        
      </div>
    </header>
        {children}
      </body>
    </html>
  );
}
